language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
install:
  - pip install -q Django==$DJANGO_VERSION
script:
  - cd example
  - python -Wall manage.py test fieldbook

